apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - postgree-secrets.yaml
  - openrouter-secrets.yaml
  - github-secrets.yaml

patches:
  - target:
      kind: Application
      name: chat-api
    patch: |
      - op: add
        path: /metadata/labels/env
        value: dev
      - op: replace
        path: /spec/source/helm/valueFiles
        value:
          - values.yaml
      - op: add
        path: /spec/source/helm/values
        value: |
          image:
            tag: "1.1.7"
          replicaCount: 2
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 512Mi
          ingress:
            enabled: true
            host: chat-dev.syncjob.ru
