apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chat-api
  namespace: chat-api
  annotations:
    argocd.argoproj.io/sync-wave: "3"  # После ingress-nginx
    # cert-manager.io/cluster-issuer: letsencrypt-dns
    # nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    ingress.kubernetes.io/ssl-redirect: "true"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - chat.syncjob.ru
      secretName: wildcard-syncjob-tls
  rules:
    - host: chat.syncjob.ru
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: chat-api
                port:
                  number: 80