apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chat-api
  namespace: argocd
  labels:
    app.kubernetes.io/name: chat-api
    app.kubernetes.io/part-of: chat
    app.kubernetes.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    # Image Updater annotations
    argocd-image-updater.argoproj.io/image-list: chat=ghcr.io/justgithubaccount/chat-api:^1
    argocd-image-updater.argoproj.io/chat.update-strategy: semver
    argocd-image-updater.argoproj.io/chat.helm.image-tag: image.tag
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main
spec:
  project: default
  source:
    repoURL: https://github.com/justgithubaccount/app-poly-gitops-helm
    targetRevision: main
    path: .
    helm:
      valueFiles:
        - values.yaml
  destination:
    name: in-cluster
    namespace: chat-api
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
